[tool.poetry]
name = "MLutilities"
version = "1.0.0-dev"
description = "Library to teach Machine Learning"
authors = ["omarcastano <omar.castano@udea.edu.co>"]
packages = [
    { include = "MLutilities/Classification"}
]

[tool.poetry.dependencies]
python = ">=3.7, <3.9.0"
numpy = "^1.21.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
