[tool.poetry]
name = "MLutilities"
version = "1.0.0-dev"
description = "Library to teach Machine Learning"
authors = ["omarcastano <omar.castano@udea.edu.co>"]
packages = [
    { include = "MLutilities/Classification"},
    { include = "MLutilities"}
]

[tool.poetry.dependencies]
python = ">=3.7, <3.9.0"
numpy = "^1.21.6"
matplotlib = "^3.5.2"
ipywidgets = "^7.7.1"
scipy = "^1.4.1"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.4.3"
jupyterlab-vim = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
